/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.JOptionPane;
import sys.crudTable;
import javax.swing.JFrame;
import com.sun.jdi.connect.spi.Connection;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import sys.crudTable;
import Ujikoding_2210010396.*;

/**
 *
 * @author ASUS
 */
public class FrameKHS extends javax.swing.JFrame {
String JudulKolom[] = {"npm", "nama", "ips1", "ips2", "ips3", "ips4", "ips5", "ips6", "ips7", "ipk"};
int LebarKolom[] = {150, 300, 100, 100, 100, 100, 100, 100, 100, 100};
String SQL = "SELECT * FROM khs";

    private crudTable myObject;

    /**
     * Creates new form FrameKHS
     */
    public FrameKHS() {
        initComponents();
        this.setLocationRelativeTo(null);
        myObject = new crudTable();
        myObject.settingJudulTabel(tabelkhs, JudulKolom);
        myObject.settingLebarKolom(tabelkhs, LebarKolom);
        myObject.tampilTabel(tabelkhs, SQL, JudulKolom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtnpm = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtips1 = new javax.swing.JTextField();
        txtips2 = new javax.swing.JTextField();
        txtips3 = new javax.swing.JTextField();
        txtips4 = new javax.swing.JTextField();
        txtips5 = new javax.swing.JTextField();
        txtips6 = new javax.swing.JTextField();
        txtips7 = new javax.swing.JTextField();
        txtipk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelkhs = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("NPM");

        jLabel2.setText("NAMA");

        jLabel3.setText("IPS 1");

        jLabel4.setText("IPS 2");

        jLabel5.setText("IPS 3");

        jLabel6.setText("IPS 4");

        jLabel7.setText("IPS 5");

        jLabel8.setText("IPS 6");

        jLabel9.setText("IPS 7");

        jLabel10.setText("IPK");

        txtnpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnpmActionPerformed(evt);
            }
        });

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtips2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtips2ActionPerformed(evt);
            }
        });

        txtips5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtips5ActionPerformed(evt);
            }
        });

        txtips7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtips7ActionPerformed(evt);
            }
        });

        tabelkhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelkhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelkhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelkhs);

        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UBAH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("CETAK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addComponent(jLabel10))
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtips6)
                            .addComponent(txtips5)
                            .addComponent(txtips4)
                            .addComponent(txtips3)
                            .addComponent(txtnpm)
                            .addComponent(txtnama)
                            .addComponent(txtips1)
                            .addComponent(txtips2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtips7)
                            .addComponent(txtipk, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtnpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtips1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtips2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtips3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtips4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtips5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtips6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtips7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtipk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtips7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtips7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtips7ActionPerformed

    private void txtnpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnpmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnpmActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtips2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtips2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtips2ActionPerformed

    private void txtips5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtips5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtips5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        // Ambil data dari form
        String npm = txtnpm.getText().trim();
        String nama = txtnama.getText().trim();
        double ips1 = Double.parseDouble(txtips1.getText().trim());
        double ips2 = Double.parseDouble(txtips2.getText().trim());
        double ips3 = Double.parseDouble(txtips3.getText().trim());
        double ips4 = Double.parseDouble(txtips4.getText().trim());
        double ips5 = Double.parseDouble(txtips5.getText().trim());
        double ips6 = Double.parseDouble(txtips6.getText().trim());
        double ips7 = Double.parseDouble(txtips7.getText().trim());

        // Hitung IPK (rata-rata dari IPS1 hingga IPS7)
        double ipk = (ips1 + ips2 + ips3 + ips4 + ips5 + ips6 + ips7) / 7;

        // Format IPK menjadi 2 angka di belakang koma (opsional)
        ipk = Math.round(ipk * 100.0) / 100.0;

        // Simpan data ke database menggunakan fungsi CRUD dinamis
        String[] fields = {"npm", "nama", "ips1", "ips2", "ips3", "ips4", "ips5", "ips6", "ips7", "ipk"};
        String[] values = {
            npm,
            nama,
            String.valueOf(ips1),
            String.valueOf(ips2),
            String.valueOf(ips3),
            String.valueOf(ips4),
            String.valueOf(ips5),
            String.valueOf(ips6),
            String.valueOf(ips7),
            String.valueOf(ipk)
        };
        myObject.SimpanDinamis("khs", fields, values);

        // Tampilkan IPK ke text field atau area lain di GUI
        txtipk.setText(String.valueOf(ipk));

        // Berikan notifikasi kepada pengguna
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan! IPK: " + ipk);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harap masukkan nilai IPS dengan format angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
        myObject.tampilTabel(tabelkhs, SQL, JudulKolom);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
        // Ambil data dari form
        String npm = txtnpm.getText().trim();
        String nama = txtnama.getText().trim();
        double ips1 = Double.parseDouble(txtips1.getText().trim());
        double ips2 = Double.parseDouble(txtips2.getText().trim());
        double ips3 = Double.parseDouble(txtips3.getText().trim());
        double ips4 = Double.parseDouble(txtips4.getText().trim());
        double ips5 = Double.parseDouble(txtips5.getText().trim());
        double ips6 = Double.parseDouble(txtips6.getText().trim());
        double ips7 = Double.parseDouble(txtips7.getText().trim());

        // Hitung ulang IPK (rata-rata dari IPS1 hingga IPS7)
        double ipk = (ips1 + ips2 + ips3 + ips4 + ips5 + ips6 + ips7) / 7;

        // Format IPK menjadi 2 angka di belakang koma (opsional)
        ipk = Math.round(ipk * 100.0) / 100.0;

        // Data yang akan diupdate
        String[] fields = {"nama", "ips1", "ips2", "ips3", "ips4", "ips5", "ips6", "ips7", "ipk"};
        String[] values = {
            nama,
            String.valueOf(ips1),
            String.valueOf(ips2),
            String.valueOf(ips3),
            String.valueOf(ips4),
            String.valueOf(ips5),
            String.valueOf(ips6),
            String.valueOf(ips7),
            String.valueOf(ipk)
        };

        // Update data menggunakan fungsi CRUD dinamis
        String[] isiPrimary = {"npm"}; 
            myObject.UbahDinamis("khs", "npm", txtnpm.getText(), fields, values);

        // Tampilkan kembali data ke tabel
        myObject.tampilTabel(tabelkhs, SQL, JudulKolom);
        txtipk.setText(String.valueOf(ipk));

        // Berikan notifikasi kepada pengguna
        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harap masukkan nilai IPS dengan format angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String primaryKey = "npm";
            String primaryValue = txtnpm.getText();
            
            txtnpm.setText("");
            txtnama.setText("");
            txtips1.setText("");
            txtips2.setText("");
            txtips3.setText("");
            txtips4.setText("");
            txtips5.setText("");
            txtips6.setText("");
            txtips7.setText("");
            txtipk.setText("");
        myObject.HapusDinamis("khs", "npm", txtnpm.getText());
        myObject.tampilTabel(tabelkhs, SQL, JudulKolom);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      
    }//GEN-LAST:event_formMouseClicked

    private void tabelkhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelkhsMouseClicked
        int selectedRow = tabelkhs.getSelectedRow();
        if (selectedRow != -1) {
            txtnpm.setText(tabelkhs.getValueAt(selectedRow, 0).toString());
            txtnama.setText(tabelkhs.getValueAt(selectedRow, 1).toString());
            txtips1.setText(tabelkhs.getValueAt(selectedRow, 2).toString());
            txtips2.setText(tabelkhs.getValueAt(selectedRow, 3).toString());
            txtips3.setText(tabelkhs.getValueAt(selectedRow, 4).toString());
            txtips4.setText(tabelkhs.getValueAt(selectedRow, 5).toString());
            txtips5.setText(tabelkhs.getValueAt(selectedRow, 6).toString());
            txtips6.setText(tabelkhs.getValueAt(selectedRow, 7).toString());
            txtips7.setText(tabelkhs.getValueAt(selectedRow, 8).toString());
            txtipk.setText(tabelkhs.getValueAt(selectedRow, 9).toString());
        }
    }//GEN-LAST:event_tabelkhsMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String laporanfile = "src/Laporan/reportKHS.jrxml";
            String SQL = "SELECT * FROM khs";
            
            myObject.tampilLaporan(laporanfile, SQL);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameKHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameKHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameKHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameKHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameKHS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelkhs;
    private javax.swing.JTextField txtipk;
    private javax.swing.JTextField txtips1;
    private javax.swing.JTextField txtips2;
    private javax.swing.JTextField txtips3;
    private javax.swing.JTextField txtips4;
    private javax.swing.JTextField txtips5;
    private javax.swing.JTextField txtips6;
    private javax.swing.JTextField txtips7;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnpm;
    // End of variables declaration//GEN-END:variables
}
